version: "3.9"

services:
  postgres:
    image: postgres:16.9-bookworm
    container_name: polyMarket_postgres
    environment:
      POSTGRES_USER: polyMarket
      POSTGRES_PASSWORD: polyMarket
      POSTGRES_DB: polyMarket
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.1-alpine
    container_name: polyMarket_redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  nats:
    image: nats:2.11.3-alpine3.21
    container_name: polyMarket_nats
    command: -js
    expose:
      - "4222"
      - "8222"
    ports:
      - "8222:8222"
      - "4222:4222"

  clickhouse:
    image: clickhouse:24.8.14
    container_name: polyMarket_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: polyMarket
      CLICKHOUSE_PASSWORD: polyMarket
      CLICKHOUSE_DB: polyMarket

  kafka:
    image: bitnami/kafka:4.0-debian-12
    container_name: polyMarket_clickhouse_backpressure_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
