services:
  postgres:
    image: postgres:16.9-bookworm
    container_name: polyMarket_postgres
    environment:
      POSTGRES_USER: polyMarket
      POSTGRES_PASSWORD: polyMarket
      POSTGRES_DB: polyMarket
    ports:
      - "5432:5432"
    networks:
      - polyMarket_network

  redis:
    image: redis:7.4.1-alpine
    container_name: polyMarket_redis
    ports:
      - "6379:6379"
    networks:
      - polyMarket_network

  nats:
    image: nats:2.11.3-alpine3.21
    container_name: polyMarket_nats
    command: -js
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
      - polyMarket_network

  clickhouse:
    image: clickhouse:24.8.14
    container_name: polyMarket_clickhouse
    networks:
      - polyMarket_network
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: polyMarket
      CLICKHOUSE_PASSWORD: polyMarket
      CLICKHOUSE_DB: polyMarket

  redpanda:
    image: redpandadata/redpanda:v24.3.14
    container_name: polyMarket_redpanda
    ports:
      - "9092:9092"
      - "18082:8082"
      - "18081:8081"
    environment:
      RP_BOOTSTRAP_USER: "polyMarket:polyMarket"
    networks:
      - polyMarket_network
    command:
      - redpanda start
      - --overprovisioned
      - --reserve-memory 0M
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://localhost:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://localhost:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --advertise-rpc-addr localhost:33145
      - --mode dev-container

    healthcheck:
      test:
        [
          "CMD",
          "rpk",
          "cluster",
          "info",
          "-X",
          "user=polyMarket",
          "-X",
          "pass=polyMarket",
        ]
      interval: 30s
      timeout: 10s
      retries: 10

networks:
  polyMarket_network:
    driver: bridge
