[package]
name = "proto-defs"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }


[build-dependencies]
prost-build = "0.13.5"
